import { Response } from 'express';
import { AuthorizedRequest } from '../middleware/rbac';
import prisma from '@syncforge/db';

export const listComments = async (req: AuthorizedRequest, res: Response) => {
  try {
    const { projectId, pageId } = req.params;

    const page = await prisma.page.findFirst({
      where: {
        id: pageId,
        projectId,
      }
    });

    if (!page) {
      return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Page not found.' } });
    }

    const comments = await prisma.comment.findMany({
      where: { pageId },
      include: {
        author: {
          select: { id: true, displayName: true }
        }
      },
      orderBy: { createdAt: 'asc' }
    });

    return res.json({ comments });
  } catch (error) {
    console.error('Error listing comments:', error);
    return res.status(500).json({ error: { code: 'INTERNAL_ERROR', message: 'Failed to fetch comments' } });
  }
};

export const createComment = async (req: AuthorizedRequest, res: Response) => {
  try {
    const { projectId, pageId } = req.params;
    const { content, id } = req.body; // accept optional id generated by frontend for mark linking

    const page = await prisma.page.findFirst({
      where: {
        id: pageId,
        projectId,
      }
    });

    if (!page) {
      return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Page not found.' } });
    }

    if (req.workspaceMember!.role === 'VIEWER') {
      return res.status(403).json({ error: { code: 'FORBIDDEN', message: 'Viewers cannot create comments.' } });
    }

    const comment = await prisma.comment.create({
      data: {
        id, // will use provided ID or generate uuid
        pageId,
        authorId: req.user!.id,
        content
      },
      include: {
        author: {
          select: { id: true, displayName: true }
        }
      }
    });

    return res.status(201).json({ comment });
  } catch (error) {
    console.error('Error creating comment:', error);
    return res.status(500).json({ error: { code: 'INTERNAL_ERROR', message: 'Failed to create comment' } });
  }
};

export const updateComment = async (req: AuthorizedRequest, res: Response) => {
  try {
    const { projectId, pageId, commentId } = req.params;
    const { resolved } = req.body;
    const role = req.workspaceMember!.role;

    const comment = await prisma.comment.findFirst({
      where: { id: commentId, pageId }
    });

    if (!comment) {
      return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Comment not found.' } });
    }

    // Only author or admin/owner can update a comment
    if (comment.authorId !== req.user!.id && !['OWNER', 'ADMIN'].includes(role)) {
      return res.status(403).json({ error: { code: 'FORBIDDEN', message: 'Not authorized to modify this comment.' } });
    }

    const updated = await prisma.comment.update({
      where: { id: commentId },
      data: { resolved },
      include: {
        author: {
          select: { id: true, displayName: true }
        }
      }
    });

    return res.json({ comment: updated });
  } catch (error) {
    console.error('Error updating comment:', error);
    return res.status(500).json({ error: { code: 'INTERNAL_ERROR', message: 'Failed to update comment' } });
  }
};

export const deleteComment = async (req: AuthorizedRequest, res: Response) => {
  try {
    const { projectId, pageId, commentId } = req.params;
    const role = req.workspaceMember!.role;

    const comment = await prisma.comment.findFirst({
      where: { id: commentId, pageId }
    });

    if (!comment) {
      return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Comment not found.' } });
    }

    if (comment.authorId !== req.user!.id && !['OWNER', 'ADMIN'].includes(role)) {
      return res.status(403).json({ error: { code: 'FORBIDDEN', message: 'Not authorized to delete this comment.' } });
    }

    await prisma.comment.delete({ where: { id: commentId } });

    return res.status(204).send();
  } catch (error) {
    console.error('Error deleting comment:', error);
    return res.status(500).json({ error: { code: 'INTERNAL_ERROR', message: 'Failed to delete comment' } });
  }
};
